sudo: required
language: csharp
os: windows
mono: none

branches:
  only:
    - master
    - /.*/

addons:
  apt:
    packages:
      - powershell

cloneRD:
  - md ReactiveDomain
  - git clone https://github.com/ReactiveDomain/reactive-domain
  
before_script:
  - powershell -executionpolicy unrestricted -File ./tools/CheckAssemblyVersion.ps1
  
script: 
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_DIR
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_EVENT_TYPE
  - dotnet restore ./Reactive-Domain/src/ReactiveDomain.sln
  - dotnet msbuild ./Reactive-Domain/src/ReactiveDomain.sln -p:Configuration=Debug
  - dotnet msbuild ./Reactive-Domain/src/ReactiveDomain.sln -p:Configuration=Release

after_success:
  - powershell -executionpolicy unrestricted -File ./tools/CreateNuget.ps1
